eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: students
          uri: lb://students
          predicates:
            - Path=/api/students/**
        - id: schools
          uri: lb://school
          predicates:
            - Path=/api/schools/**

server:
  port: 8222

